### ISSUE TITLE
Import Failure

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lae-blacklight#75]
All minor data discrepancies cleaned up but one box causes a post to rsolr to bomb out on the staging server:

```
box_id=puls:07bx7 bin/bundle exec bin/rake lae:index_box
```

Stacktrace is a bit hard to parse. Also get a mysql error regarding the error string being too long to record in the database.

```
/opt/lae/releases/20150219212009/app/models/index_event.rb:20:in `record'
/opt/lae/releases/20150219212009/app/models/index_event.rb:66:in `index_resource'
/opt/lae/releases/20150219212009/lib/tasks/lae.rake:23:in `block (2 levels) in <top (required)>'
Mysql2::Error: Data too long for column 'error_text' at row 1
```

**Comment by kevinreiss** [comment]
Resolved.
