### ISSUE TITLE
SMTP Error

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/lae-blacklight#78]
From dev server

```
, [2015-02-23T13:38:35.636643 #15368]  INFO -- : Completed 500 Internal Server Error in 441ms
F, [2015-02-23T13:38:35.639943 #15368] FATAL -- :
ArgumentError (An SMTP From address is required to send a message. Set the message smtp_envelope_from, return_path, sender, or from address.):
  mail (2.6.3) lib/mail/check_delivery_params.rb:5:in `check_delivery_params'
  mail (2.6.3) lib/mail/network/delivery_methods/smtp.rb:98:in `deliver!'
```

**Comment by kevinreiss** [comment]
Had override record_mailer.rb to get this right.
